export const ActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  
  FETCH_PROJECTS_REQUEST: 'FETCH_PROJECTS_REQUEST',
  FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',
  
  UPDATE_PROJECT_REQUEST: 'UPDATE_PROJECT_REQUEST',
  UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAILURE: 'UPDATE_PROJECT_FAILURE',
  
  SAVE_PROJECT_REQUEST: 'SAVE_PROJECT_REQUEST',
  SAVE_PROJECT_SUCCESS: 'SAVE_PROJECT_SUCCESS',
  SAVE_PROJECT_FAILURE: 'SAVE_PROJECT_FAILURE',
  
  SYNC_PROJECTS_REQUEST: 'SYNC_PROJECTS_REQUEST',
  SYNC_PROJECTS_SUCCESS: 'SYNC_PROJECTS_SUCCESS',
  SYNC_PROJECTS_FAILURE: 'SYNC_PROJECTS_FAILURE',
  
  NOTIFICATION_RECEIVED: 'NOTIFICATION_RECEIVED',
  
  TRACK_REVISION_REQUEST: 'TRACK_REVISION_REQUEST',
  TRACK_REVISION_SUCCESS: 'TRACK_REVISION_SUCCESS',
  TRACK_REVISION_FAILURE: 'TRACK_REVISION_FAILURE',
  
  SEARCH_PROJECTS_REQUEST: 'SEARCH_PROJECTS_REQUEST',
  SEARCH_PROJECTS_SUCCESS: 'SEARCH_PROJECTS_SUCCESS',
  SEARCH_PROJECTS_FAILURE: 'SEARCH_PROJECTS_FAILURE',
  
  UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_FAILURE: 'UPLOAD_FILE_FAILURE',
  
  SEND_FEEDBACK_REQUEST: 'SEND_FEEDBACK_REQUEST',
  SEND_FEEDBACK_SUCCESS: 'SEND_FEEDBACK_SUCCESS',
  SEND_FEEDBACK_FAILURE: 'SEND_FEEDBACK_FAILURE',
  
  CHANGE_THEME: 'CHANGE_THEME',
  
  ONBOARDING_REQUEST: 'ONBOARDING_REQUEST',
  ONBOARDING_SUCCESS: 'ONBOARDING_SUCCESS',
  ONBOARDING_FAILURE: 'ONBOARDING_FAILURE',
};